/**
 * The setting line — one short line under a cross-reference saying where the
 * reader is about to land. docs/proposals/setting-line.md is the argument;
 * this is slice 1 of its §9: the BSB's own section heading, gated by how far
 * the verse sits below it, with the canonical Hebrew superscription as the
 * second link in the chain.
 *
 * What lives here, and why it is one file shared by the build and the app:
 *
 *   - THE LINE IS A FUNCTION OF THE DESTINATION VERSE ALONE (§1.2), never of
 *     the pair. That is what lets the shipped file be keyed by destination and
 *     stay small: 39,209 reachable rows point at 11,491 distinct verses.
 *   - THE RULES ARE CODE, NOT A HABIT (§4). The word cap (R4), the banned
 *     verbs (R3) and the reach gate (R6) are functions here, run by
 *     scripts/build-setting-lines.mjs over every line before it ships and
 *     again over the file it wrote. A line that breaks one is dropped, not
 *     trimmed.
 *   - NOTHING IS GENERATED BY A MODEL, EVER (§5.3, R7). Every line is a
 *     verbatim string from the BSB chapter feed, chosen at build time into a
 *     static file. There is no inference here, at build time or read time.
 *
 * The build script imports these same functions, exactly as
 * scripts/build-map-data.mjs imports src/utils/mapData.ts, so the rules the
 * build enforces and the rules the tests assert can never drift.
 *
 * Nothing below may import a Node API — this file lives under src/ and obeys
 * the pure-web rule in CLAUDE.md.
 */

/**
 * How far below its heading a verse may sit and still be described by it
 * (§4, R6). Past this, the heading is a section label that merely precedes the
 * verse — Proverbs 21:30 under "The King's Heart", 29 verses up.
 */
export const HEADING_REACH = 10

/** §4, R4: at most twelve words. A reject, never a truncation. */
export const MAX_WORDS = 12

/**
 * §4, R3: a line may never say what a passage MEANS. The list is the brief's,
 * plus the obvious spelling variants, matched on word boundaries so
 * "Meaning" fails and "Meaningful" — were it ever a heading — fails too, while
 * "Proverbs" does not trip "proves".
 */
export const BANNED_TERMS: readonly string[] = [
  'means',
  'meaning',
  'teaches',
  'shows that',
  'proves',
  'fulfils',
  'fulfills',
  'fulfilment',
  'fulfillment',
  'points to',
  'is about',
  'reminds us',
  'applies to'
]

/** Which source a line came from — rendered as its provenance (§4, R5). */
export type SettingLineSource =
  /** The BSB's editorial section heading. */
  | 'h'
  /** A canonical Hebrew superscription — part of the text, not editorial. */
  | 's'

/** One line, ready to render. */
export interface SettingLine {
  text: string
  source: SettingLineSource
}

/** `public/bible/connections/settings.json.gz` — §7.1's shape, destination-keyed. */
export interface SettingLineFile {
  v: 1
  attribution: string
  /** `{ "01015006": ["God’s Covenant with Abram", "h"] }` */
  lines: Record<string, [string, SettingLineSource]>
}

/** What the generator is given about one verse, from the BSB chapter feed. */
export interface VerseSetting {
  /** The nearest section heading above the verse, or null where there is none. */
  heading?: string | null
  /** How many verses below that heading this verse sits. 0 = the first under it. */
  sinceHeading?: number
  /** The chapter's Hebrew superscription (Psalms, Habakkuk 3), if any. */
  subtitle?: string | null
}

/** `BBCCCVVV` — the same VerseKey src/utils/mapData.ts uses, so the files join. */
export function settingLineKey(book: number, chapter: number, verse: number): string {
  return (
    String(book).padStart(2, '0') +
    String(chapter).padStart(3, '0') +
    String(verse).padStart(3, '0')
  )
}

export function wordCount(line: string): number {
  return line.trim().split(/\s+/).filter(Boolean).length
}

/** The banned term a line contains, or null. Reported by the build, never trimmed away. */
export function bannedTerm(line: string): string | null {
  const text = line.toLowerCase()
  for (const term of BANNED_TERMS) {
    const re = new RegExp(`\\b${term.replace(/ /g, '\\s+')}\\b`)
    if (re.test(text)) return term
  }
  return null
}

/** R4 and R3 together: may this string ship at all? */
export function obeysRules(line: string): boolean {
  return wordCount(line) <= MAX_WORDS && bannedTerm(line) === null
}

/**
 * The section heading, verbatim — it is already a noun phrase naming the
 * passage — or null where there is none or the verse sits outside its reach.
 */
export function headingLine(setting: VerseSetting): string | null {
  const heading = setting.heading?.replace(/\s+/g, ' ').trim()
  if (!heading) return null
  if ((setting.sinceHeading ?? 0) > HEADING_REACH) return null
  return heading
}

/**
 * A canonical Hebrew superscription, minus the musical directions, which are
 * performance instructions rather than setting: "For the choirmaster. With
 * stringed instruments. A Psalm of David." → "A Psalm of David."
 */
export function superscriptionLine(setting: VerseSetting): string | null {
  const subtitle = setting.subtitle?.replace(/\s+/g, ' ').trim()
  if (!subtitle) return null
  const kept = subtitle
    .split(/(?<=\.)\s+/)
    .filter(
      part =>
        !/^(For the choirmaster|According to|With stringed|To the tune|A song for)/i.test(
          part.trim()
        )
    )
    .join(' ')
    .trim()
  return kept.length ? kept : null
}

/**
 * The fallback chain of §5, stopping where slice 1 stops: gated heading →
 * superscription → no line at all. A row with nothing to say shows nothing,
 * exactly as the door shows no score.
 */
export function buildSettingLine(setting: VerseSetting): SettingLine | null {
  const heading = headingLine(setting)
  if (heading !== null && obeysRules(heading)) return { text: heading, source: 'h' }
  const superscription = superscriptionLine(setting)
  if (superscription !== null && obeysRules(superscription)) {
    return { text: superscription, source: 's' }
  }
  return null
}

/** One line as the build checks it: the shipped string plus how it was reached. */
export interface CheckableLine {
  key: string
  text: string
  source: SettingLineSource
  /** Verses below the heading. Only meaningful for `h`; ignored otherwise. */
  reach?: number
}

export interface RuleViolation {
  key: string
  /** 'R3' banned verb · 'R4' word cap · 'R6' out of reach. */
  rule: 'R3' | 'R4' | 'R6'
  detail: string
}

/**
 * Every rule, over a whole file. The build runs this on the lines it generated
 * AND on the gzip it wrote back, so a shipped file that breaks a rule fails the
 * build rather than a review.
 */
export function checkSettingLines(lines: readonly CheckableLine[]): RuleViolation[] {
  const violations: RuleViolation[] = []
  for (const line of lines) {
    const banned = bannedTerm(line.text)
    if (banned)
      violations.push({ key: line.key, rule: 'R3', detail: `“${banned}” in “${line.text}”` })
    const count = wordCount(line.text)
    if (count > MAX_WORDS) {
      violations.push({ key: line.key, rule: 'R4', detail: `${count} words: “${line.text}”` })
    }
    if (line.source === 'h' && (line.reach ?? 0) > HEADING_REACH) {
      violations.push({
        key: line.key,
        rule: 'R6',
        detail: `${line.reach} verses below its heading: “${line.text}”`
      })
    }
  }
  return violations
}

// ---------------------------------------------------------------------------
// Reading the shipped file, lazily
// ---------------------------------------------------------------------------

/**
 * §7.2: ONE static asset, fetched the first time a connections door opens and
 * never with the chapter. It sits under `/bible/`, which vite.config.ts's
 * workbox `globIgnores` (`**\/bible/**\/*.json.gz`) keeps out of the PWA
 * precache — the same discipline the self-hosted Bible bundles follow, for the
 * same reason: most sessions never open a door.
 */
export const SETTING_LINES_URL = '/bible/connections/settings.json.gz'

/**
 * Fetch + parse the bundle. Deliberately a copy of the sniff in
 * src/utils/mapData.ts and src/bible/self-hosted.ts: Vite's dev server tags the
 * `.gz` `Content-Encoding: gzip` and the browser hands us plain JSON, while
 * Cloudflare Pages can hand back the raw gzip stream untouched. The magic
 * number (1f 8b) cannot collide with JSON's `{` (0x7b), so sniffing is correct
 * in both rather than green in dev and broken in production.
 */
async function fetchGzJson<T>(url: string, fetchImpl: typeof fetch): Promise<T | null> {
  const res = await fetchImpl(url)
  // Null rather than an error, all the way down: a missing bundle is a door
  // with no lines on it, which is a thing the reader is allowed to see. There
  // is no code for it in src/errors.ts and there should not be one — nothing
  // above here would do anything with it but swallow it.
  if (!res.ok) return null
  const bytes = new Uint8Array(await res.arrayBuffer())
  const isGzip = bytes[0] === 0x1f && bytes[1] === 0x8b
  const json = isGzip
    ? await new Response(
        new Response(bytes).body!.pipeThrough(new DecompressionStream('gzip'))
      ).text()
    : new TextDecoder().decode(bytes)
  return JSON.parse(json) as T
}

let filePromise: Promise<SettingLineFile | null> | null = null

/**
 * The file, once — memoized on the PROMISE so two doors opening at once share
 * one download. **Never throws**: a reader who is offline and has never fetched
 * it simply sees no setting lines, exactly as §7.3 says. A failed load is not
 * remembered, so the next door tries again.
 */
export function loadSettingLines(fetchImpl?: typeof fetch): Promise<SettingLineFile | null> {
  if (!filePromise) {
    filePromise = (async () => {
      const impl = fetchImpl ?? (typeof fetch === 'function' ? fetch : null)
      if (!impl) return null
      return await fetchGzJson<SettingLineFile>(SETTING_LINES_URL, impl)
    })().catch(() => {
      filePromise = null
      return null
    })
  }
  return filePromise
}

/** The line for one verse, or null where the file has nothing to say about it. */
export function settingLineIn(
  file: SettingLineFile | null,
  book: number,
  chapter: number,
  verse: number
): SettingLine | null {
  const found = file?.lines[settingLineKey(book, chapter, verse)]
  if (!found) return null
  return { text: found[0], source: found[1] }
}
